### ISSUE TITLE
Create metadata files in an easier to read way

### ISSUE THREAD

**Issue by raymondnijssen** [IFRCGo/logos#3]
Metadata is now put in a markdown (.md) file which is hard to read in an automated process. Using json, yaml or something alike would work better, especially for the countries that have multiple logos, languages and/or websites.

**Comment by danbjoseph** [comment]
this is a good idea. would be cool to auto populate the filename field(s) with some sort of script (bash/node/python/whatever). i think YAML would be easier than json for people to edit. any other suggestions or formats you'd lean towards?

**Comment by raymondnijssen** [comment]
I tried to convert it to yaml today but I don't think people could do this easily by hand (in a way it could be parsed)
```
org:
   -  name: Afghan Red Crescent Society
      lang: en
website: http://www.redcrescent.af/
country:
    name: Afghanistan
    iso: AFG
comment:
   -  Uses 'ARCS' on website
```
